HOSTNAME: localhost
PORT: 9005
RUN_MODE: blog
DB_HOST: "0.0.0.0"
DB_PORT: "5432"
DB_NAME: "blog"
DB_USER: "blog"
DB_PASSWORD: "blog"
REDIS_HOST: localhost:6379
REDIS_PASSWORD:
REDIS_DV: 0
BUCKET_SIZE: 10
REFILL_RATE: 4
INTERVAL: 5
